name: Run application vechtdal_woningen
on:
  push:
  schedule:
    - cron: "05 7 * * *" # every day at 9:05 am

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.ref == 'refs/heads/master'}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - name: run main.py
        run: |
          python main.py

      - uses: lassebenni/publish-to-github-action@master
        if: ${{ github.event_name == 'schedule' || github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
